### ISSUE TITLE
not able to imported this node

### ISSUE THREAD

**Issue by rongtian0927** [Ryuukeisyou/comfyui_face_parsing#33]
Traceback (most recent call last):
  File "D:\ComfyUI_windows_portable_nvidia\ComfyUI\nodes.py", line 2112, in load_custom_node
    module_spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "D:\ComfyUI_windows_portable_nvidia\ComfyUI\custom_nodes\comfyui_face_parsing\__init__.py", line 29, in <module>
    import pkg_resources
  File "D:\ComfyUI_windows_portable_nvidia\python_embeded\Lib\site-packages\pkg_resources\__init__.py", line 2192
    register_finder(pkgutil.ImpImporter, find_on_path)
    ^^^^^^^^^^^^^^^
IndentationError: expected an indented block after 'if' statement on line 2191

Cannot import D:\ComfyUI_windows_portable_nvidia\ComfyUI\custom_nodes\comfyui_face_parsing module for custom nodes: expected an indented block after 'if' statement on line 2191 (__init__.py, line 2192)

I have download requirment folder from hugging face and reinstall the opencv. still not able to import node, please help thank you

**Comment by Czargasm** [comment]
I had a similar problem and I fixed it by updating setuptools

pip install --upgrade setuptools

It's some problem with using python 3.12 but this seems to fix it.

**Comment by schneegecko** [comment]
still have the issue on:
ComfyUI: v0.3.27-7-g0a1f8869
         (2025-03-27)
Manager: V3.31.8
comfyui portable,

did:


`H:\sd\ComfyUI_windows_portable\python_embeded>py -m pip install setuptools
Requirement already satisfied: setuptools in c:\python311\lib\site-packages (65.5.0)

H:\sd\ComfyUI_windows_portable\python_embeded>py -m pip install --upgrade setuptools 
Requirement already satisfied: setuptools in c:\python311\lib\site-packages (65.5.0)
Collecting setuptools
  Using cached setuptools-78.1.0-py3-none-any.whl.metadata (6.6 kB)
Using cached setuptools-78.1.0-py3-none-any.whl (1.3 MB)
Installing collected packages: setuptools
  Attempting uninstall: setuptools
    Found existing installation: setuptools 65.5.0
    Uninstalling setuptools-65.5.0:
      Successfully uninstalled setuptools-65.5.0
Successfully installed setuptools-78.1.0`

not no changes, any idea?

The very same package works in comfyui desktop 4.32, but not in portable, they use the same folder...
